### PR TITLE
Add Material App and Cupertino App

### PR DESCRIPTION
**Pull request by rubensdemelo**
Some times we just want to play around. Write some code, test, change, debug, re-write, whatever... and the easiest way to do that is starting from scratch. These snippets can help.

### CODE REVIEW

**Comment by Nash0x7E2** [comment]
Hi, 
It looks

**Comment by Nash0x7E2** [comment]
Hi, 
Sorry for accidentally closing.
While looking at the changes, I noticed that you are using a CupertinoApp for your Material snippet and a MaterialApp for your Cupertino snippet. Please update the bodies of both snippets so than they produce the correct code based on the snippet name.
https://github.com/rubensdemelo/awesome-flutter-snippets/blob/bb328c45bc07c08f27071b4a6cea7a0f36f97831/snippets/snippets.json#L338

**Comment by rubensdemelo** [comment]
Hi, sorry for that. Fixed it.

**Comment by Nash0x7E2** [comment]
Cool, merged!

**Pull request merged**
